### ISSUE TITLE
关于Eureka单机版和集群版 服务无法注册的问题

### ISSUE THREAD

**Issue by Allwayz** [zzyybs/atguigu_spirngcloud2020#4]
# 阳哥你好， 我跟着你的课程学习到了eureka的部分

>现在问题是这样的：
>Eureka的注册中心不能够找到本地启动的其他服务。

代码我是跟着你手敲的。
eureka注册中心，无论是单机版还是集群版，启动都没有问题。
我测试过将eureka注册中心自己注册到eureka服务中
网页上可以显示出当前以注册实例：**CLOUD-EUREKA-SERVER**

可是当我启动**Payment**和**Order**服务之后，eureka网页上却显示不出来这两个实例。

------
这是7001的application.yml 其他的都是大同小异
```yml
server:
  port: 7001

spring:
  application:
    name: eureka-service

eureka:
  instance: #Eureka实例名称
    hostname: eureka7001.com
  client:
    registerWithEureka: true  #false表示不向注册中心注册自己。
    fetchRegistry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka
  server:
    enableSelfPreservation: false   #开发阶段关闭eureka自我保护机制
```

------

[7001的图片](https://allwayz-blog-1259174617.cos.ap-shanghai.myqcloud.com/SpringCloud/7001.png)
[7002的图片](https://allwayz-blog-1259174617.cos.ap-shanghai.myqcloud.com/SpringCloud/7002.png)
[微服务图片](https://allwayz-blog-1259174617.cos.ap-shanghai.myqcloud.com/SpringCloud/runDashBoard.png
)

这里是当前出错的[项目地址](https://gitee.com/allwayz/MyCloud/releases/MyCloud-EurekaError)
